FROM php:8.1-apache

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN apt-get update && apt-get install -y git unzip tzdata dnsutils \
 && apt-get clean

RUN chmod +x /usr/local/bin/install-php-extensions && sync && \
    install-php-extensions opcache pdo_mysql openssl gd \
 && mv "$PHP_INI_DIR/php.ini-production" "$PHP_INI_DIR/php.ini"

RUN a2enmod rewrite
